

#1# load R packages and data
library(iCAMP)
library(ape)
com.file="otu_table.csv"
tree.file="otu_tree.nwk"
comm=t(read.csv(com.file, header = TRUE, row.names = 1,stringsAsFactors = FALSE))
tree=read.tree(file = tree.file)


#2# match OTU IDs in OTU table and tree file
spid.check=match.name(cn.list=list(comm=comm),tree.list=list(tree=tree))
#for the example data, the output should be "All match very well".
#for your data files, if you have not matched the IDs before, the unmatched OTUs will be removed.
comm=spid.check$comm
tree=spid.check$tree

#2# key parameter setting
rand.time=1000  #randomization time, 1000 is usually enough. For example test, you may set as 100 or less to save time.
nworker=26 #nworker is thread number for parallel computing, which depends on the CPU core number of your computer.
memory.G=400 #to set the memory size as you need (but should be less than the available space in your hard disk), so that calculation of large tree will not be limited by physical memory. unit is Gb.

#the folder to save the output. 
save.wd="/folder/to/save/the/output"

#3# calculate pairwise phylogenetic distance matrix.
#since microbial community data usually has a large number of species (OTUs or ASVs), we use "big.matrix" in R package "bigmemory" to handle the large phylogenetic distance matrix. 
setwd(save.wd)
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G, output = TRUE)
  #output files:
  #path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
  #pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
  #pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
  #pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.

bNTI=bNTIn.p(comm=comm, dis=pd.big, nworker = nworker, memo.size.GB = memory.G,
             weighted = TRUE, exclude.consp = FALSE, rand = rand.time,
             output.bMNTD = FALSE, sig.index = "bNTI", unit.sum = NULL,
             correct.special = TRUE, detail.null = FALSE,
             special.method = "MNTD")

bnit_results=bNTI$index
write.csv(bnit_results,file="bnit_results_bNTI.csv")

